import matplotlib.pyplot as plt 
import matplotlib.image as mpimg
import pyttsx3
engine = pyttsx3.init() 

ch="y"
while(ch=='y'):
    print('1.About Andaman and Nicobar Islands \t 2.About Lakshadweep Islands')
    engine.say("1.About Andaman and Nicobar Islands \t 2.About Lakshadweep Islands")
    engine.runAndWait()
    c=int(input("Enter your Choice: "))
    if c==1:
        plt.xticks([])
        plt.yticks([])
        img = mpimg.imread("andaman1img.jpg")
        plt.imshow(img)
        plt.show()
        print('Choose an option \n 1.Climate \t 2.Habitat \t 3.Location \t 4.Islands')
        engine.say("Choose an option \n 1.Climate \t 2.Habitat \t 3.Location \t 4.Islands")
        # engine.runAndWait()
        op = int(input("Enter your option:"))
        if op == 1:
            plt.xticks([])
            plt.yticks([])
            img = mpimg.imread("andamanmap.jpg")
            print("The climate is tropical, hot all year round, with a dry season from January to April and a rainy season from May to November due to the Indian monsoon.The temperatures are stable throughout the year, however, in March and April, the hottest time of the year occurs.")
            plt.imshow(img)
            plt.show()
            engine.say('The climate is tropical, hot all year round, with a dry season from January to April and a rainy season from May to November due to the Indian monsoon.The temperatures are stable throughout the year, however, in March and April, the hottest time of the year occurs.')
            engine.runAndWait()
        elif op == 2:
            plt.xticks([])
            plt.yticks([])
            engine.say('Andaman consists of 372 Islands with only 36 Inhabited, Havelock Island, Sentinel Island, Car Nicobar Islands. The North Sentinel Island is one of dangerous islands whihc contains the Tribal People and are hostile to outside world.')
            engine.runAndWait()
            img = mpimg.imread("andamanmap.jpg")
            plt.imshow(img)
            plt.show()
        elif op == 3:
            plt.xticks([])
            plt.yticks([])
            engine.say('Andaman consists of 372 Islands with only 36 Inhabited, Havelock Island, Sentinel Island, Car Nicobar Islands. The North Sentinel Island is one of dangerous islands whihc contains the Tribal People and are hostile to outside world.')
            engine.runAndWait()
            img = mpimg.imread("andamanmap.jpg")
            plt.imshow(img)
            plt.show()
        elif op == 4:
            plt.xticks([])
            plt.yticks([])
            img = mpimg.imread("andamanmap.jpg")
            print("'Andaman consists of 372 Islands with only 36 Inhabited, Havelock Island, Sentinel Island, Car Nicobar Islands. The North Sentinel Island is one of dangerous islands whihc contains the Tribal People and are hostile to outside world.")
            plt.imshow(img)
            plt.show()
            engine.say('Andaman consists of 372 Islands with only 36 Inhabited, Havelock Island, Sentinel Island, Car Nicobar Islands. The North Sentinel Island is one of dangerous islands whihc contains the Tribal People and are hostile to outside world.')
            engine.runAndWait()
            
    elif c==2:
        plt.xticks([])
        plt.yticks([])
        img = mpimg.imread("lakshadweep1img.jpg")
        plt.imshow(img)
        plt.show()
        print('Choose an option \n 1.Climate \t 2.Habitat \t 3.Location \t 4.Islands')
        op = int(input("Enter your option:"))
        if op == 1:
            plt.xticks([])
            plt.yticks([])
            engine.say('Lakshadweep contains 36 Islands(10 inhabited), Amini, Laccadive Minicoy and Agatti are main Islands')
            engine.runAndWait()
            img = mpimg.imread("lakshadweepmap.jpg")
            plt.imshow(img)
            plt.show()
        elif op == 2:
            plt.xticks([])
            plt.yticks([])
            engine.say('Lakshadweep contains 36 Islands(10 inhabited), Amini, Laccadive Minicoy and Agatti are main Islands')
            engine.runAndWait()
            img = mpimg.imread("lakshadweepmap.jpg")
            plt.imshow(img)
            plt.show()
        elif op == 3:
            plt.xticks([])
            plt.yticks([])
            engine.say('Lakshadweep contains 36 Islands(10 inhabited), Amini, Laccadive Minicoy and Agatti are main Islands')
            engine.runAndWait()
            img = mpimg.imread("lakshadweepmap.jpg")
            plt.imshow(img)
            plt.show()
        elif op == 4:
            plt.xticks([])
            plt.yticks([])
            engine.say('Lakshadweep contains 36 Islands(10 inhabited), Amini, Laccadive Minicoy and Agatti are main Islands')
            engine.runAndWait()
            img = mpimg.imread("lakshadweepmap.jpg")
            plt.imshow(img)
            plt.show()
ch=input("continue :")